adding:
  permissions:
    - 'create faq content'
    - 'delete faq revisions'
    - 'delete own faq content'
    - 'edit any faq content'
    - 'edit own faq content'
    - 'enter faq revision log entry'
    - 'override faq published option'
    - 'rabbit hole bypass taxonomy_term'
    - 'revert faq revisions'
    - 'view faq revisions'
removing: {  }
