adding: {  }
removing:
  dependencies:
    config:
      - core.entity_view_display.fragment.region_item.default
      - core.entity_view_display.node.page.default
      - media.type.video
    module:
      - fragments
      - layout_builder
      - replicate_ui
  permissions:
    - 'access fragments overview'
    - 'administer news feeds'
    - 'configure all page node layout overrides'
    - 'configure all region_item fragment layout overrides'
    - 'configure any layout'
    - 'configure editable page node layout overrides'
    - 'configure editable region_item fragment layout overrides'
    - 'create and edit custom blocks'
    - 'create region_item fragments'
    - 'create video media'
    - 'delete any video media'
    - 'delete own region_item fragments'
    - 'delete own video media'
    - 'delete region_item fragments'
    - 'edit any video media'
    - 'edit own video media'
    - 'replicate entities'
    - 'update own region_item fragments'
    - 'update region_item fragments'
    - 'view region_item fragments'
