image_fields:
  media--image--field_media_image--full__ultrawide: '1'
  media--image--field_media_image--full__no_crop: '1'
  media--image--field_media_image--full__square: '1'
  media--image--field_media_image--full__widescreen: '1'
  media--image--field_media_image--image_gallery: '1'
  media--image--field_media_image--image_large: '1'
  media--image--field_media_image--image_medium: '1'
  media--image--field_media_image--image_small: '1'
  media--image--field_media_image--large__no_crop: '1'
  media--image--field_media_image--large__square: '1'
  media--image--field_media_image--large__ultrawide: '1'
  media--image--field_media_image--large__widescreen: '1'
  media--image--field_media_image--medium__no_crop: '1'
  media--image--field_media_image--medium__square: '1'
  media--image--field_media_image--medium__ultrawide: '1'
  media--image--field_media_image--medium__widescreen: '1'
  media--image--field_media_image--sitenow_16_9: '1'
  media--image--field_media_image--small__no_crop: '1'
  media--image--field_media_image--small__square: '1'
  media--image--field_media_image--small__ultrawide: '1'
  media--image--field_media_image--small__widescreen: '1'
  media--image--field_media_image--edgy: '1'
  media--image--field_media_image--default: '1'
alter_tag:
  img: img
  iframe: '0'
formatters:
  lazy_image: '0'
  lazy_responsive_image: '0'
skipClass: no-lazy
disabled_paths: "/rss.xml\r\n/entity-browser/*\r\n/entity-embed/*\r\n/media/*"
placeholderSrc: ''
preferNative: false
lazysizes:
  lazyClass: lazyload
  loadedClass: lazyloaded
  loadingClass: lazyloading
  preloadClass: lazypreload
  errorClass: lazyerror
  autosizesClass: lazyautosizes
  srcAttr: data-src
  srcsetAttr: data-srcset
  sizesAttr: data-sizes
  minSize: 40
  customMedia: {  }
  init: true
  expFactor: 1.5
  hFac: 0.8
  loadMode: 2
  loadHidden: true
  ricTimeout: 0
  throttleDelay: 125
  plugins:
    aspectratio: aspectratio
_core:
  default_config_hash: 1TShnSplWum3f2DJ6uq-OQsANqeYJVltsSdViV_YY7Y
cssEffect: true
