sitenow_articles.settings:
  type: config_object
  label: 'SiteNow Articles settings'
  mapping:
    featured_image_display_default:
      type: string
      label: Featured image display default
    tag_display:
      type: string
      label: Tag display default
    related_display:
      type: string
      label: Related content display default
    show_visual_indicators_on_teasers:
      type: boolean
      label: Show arrows linking to pages from lists/teasers
