sitenow_articles.settings:
  type: config_object
  label: 'SiteNow Articles settings'
  mapping:
    featured_image_display_default:
      type: string
      label: Featured image display default
    tag_display:
      type: string
      label: Tag display default
    related_display:
      type: string
      label: Related content display default
    show_teaser_link_indicator:
      type: boolean
      label: Show arrows linking to pages from lists/teasers
    preserved_links_message_display:
      type: text
      label: Specified preserved links message
    preserved_links_message_display_default:
      type: text
      label: Default preserved links message
    display_articles_by_author:
      type: boolean
      label: Show articles authored by a person on their page.
