adding:
  weight: -8
  permissions:
    - 'create ighn_person content'
    - 'delete ighn_person revisions'
    - 'delete own ighn_person content'
    - 'edit any ighn_person content'
    - 'edit own ighn_person content'
    - 'enter ighn_person revision log entry'
    - 'override ighn_person published option'
    - 'revert ighn_person revisions'
    - 'view ighn_person revisions'
removing:
  weight: -6
  permissions:
    - 'configure editable page node layout overrides'
    - 'create and edit custom blocks'
    - 'create featured_content block content'
    - 'delete any featured_content block content'
    - 'update any featured_content block content'
