auto_entitylabel.settings.*:
  type: config_object
  label: 'Auto entity label settings'
  mapping:
    status:
      type: integer
      label: 'Automatic label generation'
    pattern:
      type: string
      label: 'Pattern for the label'
    escape:
      type: boolean
      label: 'Remove special characters'
    dependencies:
      type: config_dependencies
      label: 'Dependencies'
