adding:
  dependencies:
    config:
      - taxonomy.vocabulary.a_z_list
  permissions:
    - 'administer external-quick-links menu items'
    - 'administer search-links menu items'
    - 'create terms in a_z_list'
    - 'create uiowa_spacer_separator block content'
    - 'create uiowa_vertical_video block content'
    - 'delete any uiowa_vertical_video block content'
    - 'delete terms in a_z_list'
    - 'edit terms in a_z_list'
    - 'update any uiowa_vertical_video block content'
removing: {  }
