adding:
  dependencies:
    config:
      - field.storage.node.field_area_of_study_degree_types
  display:
    areas_of_study_block:
      display_options:
        fields:
          field_area_of_study_degree_types:
            id: field_area_of_study_degree_types
            table: node__field_area_of_study_degree_types
            field: field_area_of_study_degree_types
            relationship: none
            group_type: group
            admin_label: ''
            plugin_id: field
            label: 'Degree Types'
            exclude: false
            alter:
              alter_text: false
              text: ''
              make_link: false
              path: ''
              absolute: false
              external: false
              replace_spaces: false
              path_case: none
              trim_whitespace: false
              alt: ''
              rel: ''
              link_class: ''
              prefix: ''
              suffix: ''
              target: ''
              nl2br: false
              max_length: 0
              word_boundary: true
              ellipsis: true
              more_link: false
              more_link_text: ''
              more_link_path: ''
              strip_tags: false
              trim: false
              preserve_tags: ''
              html: false
            element_type: ''
            element_class: ''
            element_label_type: ''
            element_label_class: ''
            element_label_colon: true
            element_wrapper_type: ''
            element_wrapper_class: ''
            element_default_classes: true
            empty: ''
            hide_empty: false
            empty_zero: false
            hide_alter_empty: true
            click_sort_column: target_id
            type: entity_reference_label
            settings:
              link: false
            group_column: target_id
            group_columns: {  }
            group_rows: true
            delta_limit: 0
            delta_offset: 0
            delta_reversed: false
            delta_first_last: false
            multi_type: separator
            separator: ', '
            field_api_classes: false
        filters:
          field_area_of_study_locations_target_id:
            expose:
              label: 'Area of Study'
      cache_metadata:
        tags:
          - 'config:field.storage.node.field_area_of_study_degree_types'
removing:
  display:
    areas_of_study_block:
      display_options:
        filters:
          field_area_of_study_locations_target_id:
            expose:
              label: Locations
