module:
  acquia_connector: 0
  automated_cron: 0
  better_normalizers: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  components: 0
  config: 0
  config_actions: 0
  config_actions_provider: 0
  config_distro: 0
  config_filter: 0
  config_merge: 0
  config_normalizer: 0
  config_snapshot: 0
  config_split: 0
  config_sync: 0
  config_update: 0
  contextual: 0
  crop: 0
  ctools: 0
  date_recur: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  entity_types: 0
  entity_types_page: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  hal: 0
  heading: 0
  help: 0
  history: 0
  image: 0
  layout_builder: 0
  layout_builder_custom: 0
  layout_builder_restrictions: 0
  layout_builder_styles: 0
  layout_discovery: 0
  lb_direct_add: 0
  link: 0
  linkit: 0
  media: 0
  media_core: 0
  media_document: 0
  media_image: 0
  media_library: 0
  media_library_theme_reset: 0
  media_video: 0
  memcache: 0
  menu_ui: 0
  node: 0
  noreqnewpass: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  samlauth: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  uiowa_auth: 0
  uiowa_bar: 0
  uiowa_footer: 0
  uiowa_lb_blocks: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  externalauth: 10
  views: 10
  config_provider: 100
  collegiate: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  collegiate_theme: 0
  claro: 0
profile: collegiate
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
