adding:
  entity_type_groups:
    node:
      residence_hall:
        basic: basic
        advanced: advanced
        open_graph: open_graph
        twitter_cards: twitter_cards
removing:
  entity_type_groups:
    webform_submission:
      contact:
        basic: basic
