local:
  root: /var/www/html
  uri: environmentalsciences.uiowa.ddev.site
  paths:
    files: sites/environmentalsciences.uiowa.edu/files
dev:
  uri: environmentalsciences.dev.drupal.uiowa.edu
  host: uiowa01dev.ssh.prod.acquia-sites.com
  options: {  }
  paths:
    dump-dir: /mnt/tmp
    files: sites/environmentalsciences.uiowa.edu/files
  root: /var/www/html/uiowa01.dev/docroot
  user: uiowa01.dev
prod:
  uri: environmentalsciences.uiowa.edu
  host: uiowa01.ssh.prod.acquia-sites.com
  options: {  }
  paths:
    dump-dir: /mnt/tmp
    files: sites/environmentalsciences.uiowa.edu/files
  root: /var/www/html/uiowa01.prod/docroot
  user: uiowa01.prod
test:
  uri: environmentalsciences.stage.drupal.uiowa.edu
  host: uiowa01stg.ssh.prod.acquia-sites.com
  options: {  }
  paths:
    dump-dir: /mnt/tmp
    files: sites/environmentalsciences.uiowa.edu/files
  root: /var/www/html/uiowa01.test/docroot
  user: uiowa01.test
