add_on_import:
  permissions:
    - 'create topic_collection content'
    - 'delete own topic_collection content'
    - 'delete topic_collection revisions'
    - 'edit any topic_collection content'
    - 'edit own topic_collection content'
    - 'revert topic_collection revisions'
    - 'view topic_collection revisions'
remove_on_import: {  }
