adding:
  dependencies:
    config:
      - node.type.partner
      - node.type.project
      - taxonomy.vocabulary.colleges_and_departments
  permissions:
    - 'create partner content'
    - 'create project content'
    - 'create terms in colleges_and_departments'
    - 'delete any partner content'
    - 'delete any project content'
    - 'delete own partner content'
    - 'delete own project content'
    - 'delete partner revisions'
    - 'delete project revisions'
    - 'edit any partner content'
    - 'edit any project content'
    - 'edit own partner content'
    - 'edit own project content'
    - 'edit terms in colleges_and_departments'
    - 'enter partner revision log entry'
    - 'enter project revision log entry'
    - 'override partner published option'
    - 'override project published option'
    - 'revert partner revisions'
    - 'revert project revisions'
    - 'view partner revisions'
    - 'view project revisions'
removing: {  }
