adding:
  entity_type_groups:
    node:
      area_of_study:
        basic: basic
        advanced: advanced
        open_graph: open_graph
      event_series:
        basic: basic
        advanced: advanced
        open_graph: open_graph
        twitter_cards: twitter_cards
      student_profile:
        basic: basic
        advanced: advanced
        open_graph: open_graph
        schema_person: schema_person
      transfer_tips:
        basic: basic
        advanced: advanced
        open_graph: open_graph
removing: {  }
