adding:
  permissions:
    - 'enter area_of_study revision log entry'
    - 'view area_of_study revisions'
    - 'view student_profile revisions'
    - 'view transfer_tips revisions'
removing:
  permissions:
    - 'enter scholarship revision log entry'
    - 'enter event revision log entry'
