adding:
  block_restrictions:
    - 'views_block:student_card-block_1'
    - 'views_block:student_card-block_student_grid'
removing:
  block_restrictions:
    - 'inline_block:uiowa_articles'
    - 'inline_block:uiowa_people'
