adding:
  dependencies:
    config:
      - field.field.node.event.field_event_category
  content:
    field_event_category:
      type: entity_reference_label
      label: above
      settings:
        link: true
      weight: 3
      region: content
removing:
  dependencies:
    config:
      - field.field.node.event.field_event_attendance_mode
