adding:
  dependencies:
    config:
      - node.type.area_of_study
      - node.type.scholarship
      - node.type.student_profile
      - node.type.transfer_tips
  type_settings:
    entity_types:
      node:
        - area_of_study
        - scholarship
        - student_profile
        - transfer_tips
removing: {  }
