adding:
  dependencies:
    config:
      - node.type.area_of_study
      - node.type.event_series
      - node.type.major
      - node.type.student_profile
      - node.type.transfer_tips
      - taxonomy.vocabulary.academic_groups
      - taxonomy.vocabulary.colleges
      - taxonomy.vocabulary.community_colleges
  permissions:
    - 'create area_of_study content'
    - 'create event_series content'
    - 'create major content'
    - 'create stat fragments'
    - 'create student_profile content'
    - 'create terms in academic_groups'
    - 'create terms in colleges'
    - 'create terms in community_colleges'
    - 'create transfer_tips content'
    - 'delete any area_of_study content'
    - 'delete any event_series content'
    - 'delete any major content'
    - 'delete any student_profile content'
    - 'delete any transfer_tips content'
    - 'delete area_of_study revisions'
    - 'delete event_series revisions'
    - 'delete major revisions'
    - 'delete own area_of_study content'
    - 'delete own event_series content'
    - 'delete own major content'
    - 'delete own stat fragments'
    - 'delete own student_profile content'
    - 'delete own transfer_tips content'
    - 'delete stat fragments'
    - 'delete student_profile revisions'
    - 'delete terms in community_colleges'
    - 'delete transfer_tips revisions'
    - 'edit any area_of_study content'
    - 'edit any event_series content'
    - 'edit any major content'
    - 'edit any student_profile content'
    - 'edit any transfer_tips content'
    - 'edit own area_of_study content'
    - 'edit own major content'
    - 'edit own student_profile content'
    - 'edit own transfer_tips content'
    - 'edit terms in academic_groups'
    - 'edit terms in colleges'
    - 'edit terms in community_colleges'
    - 'enter area_of_study revision log entry'
    - 'enter major revision log entry'
    - 'enter student_profile revision log entry'
    - 'enter transfer_tips revision log entry'
    - 'override area_of_study published option'
    - 'override major published option'
    - 'override student_profile published option'
    - 'override transfer_tips published option'
    - 'revert area_of_study revisions'
    - 'revert major revisions'
    - 'revert person revisions'
    - 'revert student_profile revisions'
    - 'revert transfer_tips revisions'
    - 'update own stat fragments'
    - 'update stat fragments'
    - 'view area_of_study revisions'
    - 'view major revisions'
    - 'view student_profile revisions'
    - 'view transfer_tips revisions'
removing: {  }
