adding:
  dependencies:
    config:
      - core.entity_view_display.node.page.default
      - node.type.area_of_study
      - node.type.event_series
      - node.type.student_profile
      - node.type.transfer_tips
      - taxonomy.vocabulary.academic_groups
      - taxonomy.vocabulary.colleges
  permissions:
    - 'administer external-quick-links menu items'
    - 'administer search-links menu items'
    - 'create area_of_study content'
    - 'create event_series content'
    - 'create stat fragments'
    - 'create student_profile content'
    - 'create terms in academic_groups'
    - 'create terms in colleges'
    - 'create transfer_tips content'
    - 'delete any area_of_study content'
    - 'delete any event_series content'
    - 'delete any student_profile content'
    - 'delete any transfer_tips content'
    - 'delete area_of_study revisions'
    - 'delete event_series revisions'
    - 'delete own area_of_study content'
    - 'delete own event_series content'
    - 'delete own stat fragments'
    - 'delete own student_profile content'
    - 'delete own transfer_tips content'
    - 'delete stat fragments'
    - 'delete student_profile revisions'
    - 'delete terms in academic_groups'
    - 'delete terms in colleges'
    - 'delete transfer_tips revisions'
    - 'edit any area_of_study content'
    - 'edit any event_series content'
    - 'edit any student_profile content'
    - 'edit any transfer_tips content'
    - 'edit own area_of_study content'
    - 'edit own student_profile content'
    - 'edit own transfer_tips content'
    - 'edit terms in academic_groups'
    - 'edit terms in colleges'
    - 'enter area_of_study revision log entry'
    - 'enter student_profile revision log entry'
    - 'enter transfer_tips revision log entry'
    - 'override area_of_study authored by option'
    - 'override area_of_study published option'
    - 'override scholarship authored by option'
    - 'override scholarship revision option'
    - 'override student_profile authored by option'
    - 'override student_profile published option'
    - 'override student_profile revision option'
    - 'override transfer_tips authored by option'
    - 'override transfer_tips published option'
    - 'override transfer_tips revision option'
    - 'revert area_of_study revisions'
    - 'revert student_profile revisions'
    - 'revert transfer_tips revisions'
    - 'update own stat fragments'
    - 'update stat fragments'
    - 'view area_of_study revisions'
    - 'view student_profile revisions'
    - 'view transfer_tips revisions'
removing: {  }
