adding:
  dependencies:
    config:
      - node.type.alert
      - node.type.service
      - node.type.support_article
      - workflows.workflow.alert
      - workflows.workflow.draft
    module:
      - replicate_ui
  permissions:
    - 'create alert content'
    - 'create support_article content'
    - 'delete any support_article content'
    - 'delete own support_article content'
    - 'delete service revisions'
    - 'delete support_article revisions'
    - 'edit any alert content'
    - 'edit any service content'
    - 'edit any support_article content'
    - 'edit own alert content'
    - 'edit own service content'
    - 'edit own support_article content'
    - 'enter alert revision log entry'
    - 'enter service revision log entry'
    - 'enter support_article revision log entry'
    - 'replicate entities'
    - 'revert alert revisions'
    - 'revert service revisions'
    - 'revert support_article revisions'
    - 'use alert transition create_new_draft'
    - 'use alert transition needs_review'
    - 'use draft transition archived_published'
    - 'use draft transition create_new_draft'
    - 'use draft transition publish'
    - 'use editorial transition archive'
    - 'view alert revisions'
    - 'view service revisions'
    - 'view support_article revisions'
removing:
  dependencies:
    config:
      - block_content.type.uiowa_text_area
      - core.entity_view_display.fragment.region_item.default
      - core.entity_view_display.fragment.region_item_after_content.default
    module:
      - menu_admin_per_menu
  permissions:
    - 'access fragments overview'
    - 'administer main menu items'
    - 'configure editable region_item fragment layout overrides'
    - 'configure editable region_item_after_content fragment layout overrides'
    - 'create page content'
    - 'create region_item fragments'
    - 'create region_item_after_content fragments'
    - 'create uiowa_text_area block content'
    - 'delete any uiowa_text_area block content'
    - 'delete own page content'
    - 'delete page revisions'
    - 'edit any page content'
    - 'edit any uiowa_text_area block content'
    - 'edit own page content'
    - 'override page published option'
    - 'revert page revisions'
    - 'update own region_item fragments'
    - 'update own region_item_after_content fragments'
