adding:
  dependencies:
    config:
      - node.type.service
  permissions:
    - 'delete service revisions'
    - 'edit any service content'
    - 'edit own service content'
    - 'enter alert revision log entry'
    - 'enter service revision log entry'
    - 'override alert authored by option'
    - 'override alert authored on option'
    - 'override service published option'
    - 'revert alert revisions'
    - 'revert service revisions'
    - 'view service revisions'
removing:
  dependencies:
    config:
      - filter.format.webform_default
