adding:
  dependencies:
    config:
      - node.type.service
      - node.type.support_article
  permissions:
    - 'enter alert revision log entry'
    - 'enter service revision log entry'
    - 'enter support_article revision log entry'
    - 'view service revisions'
    - 'view support_article revisions'
removing: {  }
