adding:
  dependencies:
    config:
      - field.field.node.person.field_person_birth_year
      - field.field.node.person.field_person_death_year
      - field.field.node.person.field_person_nationality
  hidden:
    field_person_birth_year: true
    field_person_death_year: true
    field_person_nationality: true
    publish_on: true
    unpublish_on: true
removing: {  }
