bizhub:
  endpoint: https://bizhub.facilities.uiowa.edu/bizhub/ext/
buildui:
  endpoint: https://buildui.facilities.uiowa.edu/buildui/ext/
utility_alerts:
  endpoint: http://utils-srv.nexus.facilities.uiowa.edu/utilities/alerts/api/report
