role_mappings:
  - 'administrator|urn:oid:2.5.4.31|CN=ITS-WebServices,OU=Groups,OU=ITS,DC=iowa,DC=uiowa,DC=edu'
  - 'administrator|urn:oid:2.5.4.31|CN=ITS-Students-WebServices,OU=Groups,OU=ITS,DC=iowa,DC=uiowa,DC=edu'
  - 'requestor|urn:oid:1.3.6.1.4.1.5923.1.1.1.5|student'
  - 'requestor|urn:oid:1.3.6.1.4.1.5923.1.1.1.5|faculty'
  - 'requestor|urn:oid:1.3.6.1.4.1.5923.1.1.1.5|staff'
_core:
  default_config_hash: SJr1QVVTTte-gucsJ0GtimgsqKBVZWe6syXh5Y-Jl2I
all_valid_hawkids_can_authenticate: true
