adding:
  permissions:
    - 'create lockup content'
    - 'create terms in orgs'
    - 'delete any lockup content'
    - 'delete lockup revisions'
    - 'delete own lockup content'
    - 'delete terms in orgs'
    - 'edit any lockup content'
    - 'edit own lockup content'
    - 'edit terms in orgs'
    - 'enter lockup revision log entry'
    - 'override lockup authored by option'
    - 'override lockup published option'
    - 'revert lockup revisions'
    - 'use lockup transition archive'
    - 'use lockup transition archived_published'
    - 'use lockup transition create_new_draft'
    - 'use lockup transition deny'
    - 'use lockup transition needs_review'
    - 'use lockup transition publish'
    - 'view lockup revisions'
removing:
  permissions:
    - 'configure all page node layout overrides'
    - 'configure any layout'
    - 'configure editable page node layout overrides'
    - 'create and edit custom blocks'
    - 'create video media'
    - 'delete any video media'
    - 'delete own video media'
    - 'edit any video media'
    - 'edit own video media'
