collegiate_theme_header_alignment_settings: site-header__left
collegiate_theme_header_color_settings: site-header--primary
collegiate_theme_container_settings: page__container
_core:
  default_config_hash: jDBfafnjU_C70WrrCLwRGU7W4zf4eDJtTJYdj6xJ2J0
features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
