added:
  content:
    field_image:
      settings:
        view_mode: medium__square
    field_person_email:
      label: visually_hidden
    field_person_phone:
      label: visually_hidden
removed:
  dependencies:
    config:
      - field.field.node.person.field_grad_program_all_degree
      - field.field.node.person.field_person_university_id
      - field.field.node.person.field_pt_student_advisor
      - field.field.node.person.field_pt_student_cur_pos_inst
      - field.field.node.person.field_pt_student_cur_pos_title
      - field.field.node.person.field_pt_student_defense_date
      - field.field.node.person.field_pt_student_program_start
      - field.field.node.person.pt_student_dissertation_title
  content:
    field_image:
      settings:
        view_mode: large__square
    field_person_email:
      label: inline
    field_person_phone:
      label: inline
  hidden:
    field_grad_program_all_degree: true
    field_person_university_id: true
    field_pt_student_advisor: true
    field_pt_student_cur_pos_inst: true
    field_pt_student_cur_pos_title: true
    field_pt_student_defense_date: true
    field_pt_student_program_start: true
    pt_student_dissertation_title: true
