adding:
  dependencies:
    config:
      - node.type.alert
      - taxonomy.vocabulary.alert_categories
    module:
      - scheduler
  permissions:
    - 'create alert content'
    - 'create terms in alert_categories'
    - 'delete alert revisions'
    - 'delete any alert content'
    - 'delete own alert content'
    - 'edit any alert content'
    - 'edit own alert content'
    - 'edit terms in alert_categories'
    - 'schedule publishing of nodes'
    - 'view alert revisions'
removing: {  }
