adding:
  entity_type_groups:
    node:
      alert:
        basic: basic
        advanced: advanced
        open_graph: open_graph
        twitter_cards: twitter_cards
  tag_scroll_max_height: ''
removing: {  }
