adding:
  permissions:
    - 'add content to books'
    - 'create book content'
    - 'create terms in book_tags'
    - 'delete book revisions'
    - 'delete own book content'
    - 'edit any book content'
    - 'edit own book content'
    - 'edit terms in book_tags'
    - 'override book published option'
    - 'revert book revisions'
    - 'view book revisions'
removing:
  permissions:
    - 'edit any panopto media'
