_core:
  default_config_hash: wZ5T1cqvSG3zUPxdtz_BgdBiNjgy1K1Al-L3iT7sPh8
charts_default_settings:
  library: highcharts
  type: line
  display:
    title: ''
    title_position: out
    subtitle: ''
    data_labels: false
    data_markers: false
    legend_position: right
    background: ''
    three_dimensional: 0
    colors:
      - '#006fb0'
      - '#f07c33'
      - '#342e9c'
      - '#579b17'
      - '#3f067a'
      - '#cbde67'
      - '#7643b6'
      - '#738d00'
      - '#c157c7'
      - '#02dab1'
      - '#ed56b4'
      - '#d8d981'
      - '#004695'
      - '#736000'
      - '#a5a5ff'
      - '#833a00'
      - '#ff9ee9'
      - '#684507'
      - '#fe4f85'
      - '#5d0011'
      - '#ffa67b'
      - '#88005c'
      - '#ff9b8f'
      - '#85000f'
      - '#ff7581'
    polar: 0
    tooltips: true
    dimensions:
      width: ''
      width_units: '%'
      height: ''
      height_units: ''
    gauge:
      max: '100'
      min: '0'
      green_from: '85'
      green_to: '100'
      yellow_from: '50'
      yellow_to: '85'
      red_from: '0'
      red_to: '50'
    color_changer: false
  xaxis:
    title: ''
    labels_rotation: '0'
  yaxis:
    title: ''
    min: ''
    max: ''
    prefix: ''
    suffix: ''
    decimal_count: ''
    labels_rotation: '0'
  library_config:
    legend:
      layout: vertical
      background_color: ''
      border_width: '0'
      item_style:
        color: ''
        overflow: ''
      shadow: false
    exporting_library: false
    texture_library: false
    global_options:
      lang:
        download_CSV: 'Download CSV'
        download_JPEG: 'Download JPEG image'
        download_PDF: 'Download PDF document'
        download_PNG: 'Download PNG image '
        download_SVG: 'Download SVG vector image'
        download_XLS: 'Download XLS'
        exit_fullscreen: 'Exit from full screen'
        hide_data: 'Hide data table'
        loading: Loading...
        main_breadcrumb: Main
        thousands_sep: ' '
        decimal_point: .
        no_data: 'No data to display'
        print_chart: 'Print chart'
        reset_zoom: 'Reset zoom'
        reset_zoom_title: 'Reset zoom level 1:1'
        view_data: 'View data table'
        view_fullscreen: 'View in full screen'
        context_button_title: 'Chart context menu'
        drill_up_text: 'Back to {series.name}'
        invalid_date: 'Invalid date'
        months:
          - January
          - February
          - March
          - April
          - May
          - June
          - July
          - August
          - September
          - October
          - November
          - December
        short_months:
          - Jan
          - Feb
          - Mar
          - Apr
          - May
          - Jun
          - Jul
          - Aug
          - Sept
          - Oct
          - Nov
          - Dec
        weekdays:
          - Sunday
          - Monday
          - Tuesday
          - Wednesday
          - Thursday
          - Friday
          - Saturday
        short_weekdays:
          - Sun
          - Mon
          - Tue
          - Wed
          - Thurs
          - Frid
          - Sat
        export_data:
          annotation_header: Annotations
          category_datetime_header: DateTime
          category_header: Category
        numeric_symbols:
          - k
          - M
          - G
          - T
          - P
          - E
advanced:
  debug: false
  requirements:
    cdn: true
dependencies:
  module:
    - charts_highcharts
