adding:
  role_mappings:
    - 'requester|urn:oid:1.3.6.1.4.1.5923.1.1.1.5|student'
    - 'requester|urn:oid:1.3.6.1.4.1.5923.1.1.1.5|faculty'
    - 'requester|urn:oid:1.3.6.1.4.1.5923.1.1.1.5|staff'
    - 'requester|urn:oid:1.3.6.1.4.1.5923.1.1.1.5|affiliate'
    - 'requester|urn:oid:1.3.6.1.4.1.5923.1.1.1.5|member'
  all_valid_hawkids_can_authenticate: true
removing: {  }
