adding:
  dependencies:
    config:
      - field.field.node.person.field_person_publications_link
      - field.field.node.person.field_pt_faculty_type
      - field.field.node.person.field_pt_student_cur_pos_dept
  content:
    body:
      weight: 13
    created:
      weight: 22
    field_grad_program_all_degree:
      weight: 16
    field_meta_tags:
      weight: 33
    field_person_contact_information:
      weight: 32
    field_person_department:
      weight: 15
    field_person_education:
      weight: 14
    field_person_email:
      weight: 9
    field_person_hide:
      weight: 31
    field_person_hometown:
      weight: 12
    field_person_phone:
      weight: 10
    field_person_position:
      weight: 7
    field_person_publications_link:
      type: link_default
      weight: 34
      region: content
      settings:
        placeholder_url: ''
        placeholder_title: ''
      third_party_settings: {  }
    field_person_research_areas:
      weight: 18
    field_person_university_id:
      weight: 8
    field_person_website:
      weight: 19
    field_person_website_link_direct:
      weight: 20
    field_pt_faculty_type:
      type: options_select
      weight: 6
      region: content
      settings: {  }
      third_party_settings: {  }
    field_pt_student_advisor:
      weight: 17
    field_pt_student_cur_pos_dept:
      type: string_textfield
      weight: 39
      region: content
      settings:
        size: 60
        placeholder: ''
      third_party_settings: {  }
    field_pt_student_cur_pos_inst:
      weight: 37
    field_pt_student_cur_pos_title:
      weight: 38
    field_pt_student_defense_date:
      weight: 35
    field_pt_student_program_start:
      weight: 36
    field_tags:
      weight: 23
    field_teaser:
      weight: 30
    moderation_state:
      weight: 29
    path:
      weight: 26
    promote:
      weight: 24
    pt_student_dissertation_title:
      weight: 11
    status:
      weight: 28
    sticky:
      weight: 25
    uid:
      weight: 21
    url_redirects:
      weight: 27
removing:
  content:
    body:
      weight: 12
    created:
      weight: 21
    field_grad_program_all_degree:
      weight: 15
    field_meta_tags:
      weight: 32
    field_person_contact_information:
      weight: 31
    field_person_department:
      weight: 14
    field_person_education:
      weight: 13
    field_person_email:
      weight: 8
    field_person_hide:
      weight: 30
    field_person_hometown:
      weight: 11
    field_person_phone:
      weight: 9
    field_person_position:
      weight: 6
    field_person_research_areas:
      weight: 17
    field_person_university_id:
      weight: 7
    field_person_website:
      weight: 18
    field_person_website_link_direct:
      weight: 19
    field_pt_student_advisor:
      weight: 16
    field_pt_student_cur_pos_inst:
      weight: 35
    field_pt_student_cur_pos_title:
      weight: 36
    field_pt_student_defense_date:
      weight: 33
    field_pt_student_program_start:
      weight: 34
    field_tags:
      weight: 22
    field_teaser:
      weight: 29
    moderation_state:
      weight: 28
    path:
      weight: 25
    promote:
      weight: 23
    pt_student_dissertation_title:
      weight: 10
    status:
      weight: 27
    sticky:
      weight: 24
    uid:
      weight: 20
    url_redirects:
      weight: 26
