ignored_config_entities:
  - google_analytics.settings
  - acquia_connector.settings
  - pathauto.pattern.article
  - pathauto.pattern.person
  - system.site
  - uiowa_bar.settings
  - uiowa_footer.settings
  - views.view.articles
  - views.view.people
  - 'webform.webform.*'
  - sitenow_events.settings
enable_export_filtering: '0'
_core:
  default_config_hash: v7E8C8wJWeAW2BGohMNY1tZSBc4bexM6O62tGxecTfE
