sitenow_pages.settings:
  type: config_object
  label: 'SiteNow Pages settings'
  mapping:
    featured_image_display_default:
      type: string
      label: Featured image display default
    tag_display:
      type: string
      label: Tag display
    related_display:
      type: string
      label: Related content display
    show_teaser_link_indicator:
      type: boolean
      label: Show arrows linking to pages from lists/teasers
    card_link_indicator_display:
      type: boolean
      label: Card arrow button default
