adding:
  content:
    created:
      weight: 8
    field_image:
      weight: 4
    field_meta_tags:
      weight: 17
    field_person_bio:
      weight: 5
    field_person_hide:
      weight: 16
    field_person_website:
      weight: 6
    field_tags:
      weight: 9
    moderation_state:
      weight: 15
    path:
      weight: 12
    promote:
      weight: 10
    status:
      weight: 14
    sticky:
      weight: 11
    uid:
      weight: 7
    url_redirects:
      weight: 13
  hidden:
    field_person_contact_information: true
    field_person_credential: true
    field_person_education: true
    field_person_email: true
    field_person_phone: true
    field_person_position: true
    field_person_research_areas: true
    field_teaser: true
removing:
  dependencies:
    module:
      - paragraphs
      - telephone
  content:
    created:
      weight: 14
    field_image:
      weight: 5
    field_meta_tags:
      weight: 25
    field_person_bio:
      weight: 9
    field_person_contact_information:
      type: paragraphs
      weight: 24
      region: content
      settings:
        title: 'Contact Information'
        title_plural: 'Contact Information'
        edit_mode: open
        closed_mode: summary
        autocollapse: none
        closed_mode_threshold: 0
        add_mode: dropdown
        form_display_mode: default
        default_paragraph_type: _none
        features:
          add_above: '0'
          collapse_edit_all: collapse_edit_all
          duplicate: duplicate
      third_party_settings: {  }
    field_person_credential:
      type: string_textfield
      weight: 4
      region: content
      settings:
        size: 60
        placeholder: ''
      third_party_settings: {  }
    field_person_education:
      type: string_textarea
      weight: 10
      region: content
      settings:
        rows: 2
        placeholder: ''
      third_party_settings: {  }
    field_person_email:
      type: email_default
      weight: 7
      region: content
      settings:
        placeholder: ''
        size: 60
      third_party_settings: {  }
    field_person_hide:
      weight: 23
    field_person_phone:
      type: telephone_default
      weight: 8
      region: content
      settings:
        placeholder: ''
      third_party_settings: {  }
    field_person_position:
      type: string_textfield
      weight: 6
      region: content
      settings:
        size: 60
        placeholder: ''
      third_party_settings: {  }
    field_person_research_areas:
      type: entity_reference_autocomplete
      weight: 11
      region: content
      settings:
        match_operator: CONTAINS
        match_limit: 10
        size: 60
        placeholder: ''
      third_party_settings: {  }
    field_person_website:
      weight: 12
    field_tags:
      weight: 15
    field_teaser:
      type: string_textarea
      weight: 22
      region: content
      settings:
        rows: 5
        placeholder: ''
      third_party_settings: {  }
    moderation_state:
      weight: 21
    path:
      weight: 18
    promote:
      weight: 16
    status:
      weight: 20
    sticky:
      weight: 17
    uid:
      weight: 13
    url_redirects:
      weight: 19
