sitenow_people.person_type.*:
  type: config_entity
  label: Person Type
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
    allowed_fields:
      type: sequence
      label: 'Allowed fields'
      sequence:
        type: string
