adding:
  dependencies:
    config:
      - field.field.node.person.field_person_research_areas
      - field.field.node.person.field_person_territory
  hidden:
    field_person_research_areas: true
    field_person_territory: true
removing: {  }
