added: {  }
removed:
  entity_type_groups:
    node:
      event:
        basic: basic
        advanced: advanced
        open_graph: open_graph
        twitter_cards: twitter_cards
        schema_event: schema_event
