adding:
  dependencies:
    config:
      - node.type.event
  permissions:
    - 'access metatag schema_event__schema_event_description'
    - 'access metatag schema_event__schema_event_end_date'
    - 'access metatag schema_event__schema_event_event_status'
    - 'access metatag schema_event__schema_event_image'
    - 'access metatag schema_event__schema_event_location'
    - 'access metatag schema_event__schema_event_name'
    - 'access metatag schema_event__schema_event_start_date'
    - 'access metatag schema_event__schema_event_type'
    - 'access metatag schema_event__schema_event_url'
    - 'create event content'
    - 'delete event revisions'
    - 'delete own event content'
    - 'edit any event content'
    - 'edit own event content'
    - 'enter event revision log entry'
    - 'override event published option'
    - 'revert event revisions'
    - 'view event revisions'
removing: {  }
