adding:
  permissions:
    - 'create area_of_study content'
    - 'create grad_costs_estimate content'
    - 'create terms in colleges'
    - 'create terms in degree_types'
    - 'create terms in grad_areas_of_study'
    - 'delete area_of_study revisions'
    - 'delete grad_costs_estimate revisions'
    - 'edit any area_of_study content'
    - 'edit any grad_costs_estimate content'
    - 'edit own area_of_study content'
    - 'edit own grad_costs_estimate content'
    - 'edit terms in colleges'
    - 'edit terms in degree_types'
    - 'edit terms in grad_areas_of_study'
    - 'enter area_of_study revision log entry'
    - 'enter grad_costs_estimate revision log entry'
    - 'override area_of_study published option'
    - 'override grad_costs_estimate published option'
    - 'revert area_of_study revisions'
    - 'revert grad_costs_estimate revisions'
    - 'view area_of_study revisions'
    - 'view grad_costs_estimate revisions'
removing: {  }
