adding:
  dependencies:
    config:
      - node.type.grant
      - node.type.nonprofit_org
  permissions:
    - 'create grant content'
    - 'create nonprofit_org content'
    - 'delete grant revisions'
    - 'delete nonprofit_org revisions'
    - 'delete own grant content'
    - 'delete own nonprofit_org content'
    - 'edit any grant content'
    - 'edit any nonprofit_org content'
    - 'edit own grant content'
    - 'edit own nonprofit_org content'
    - 'enter grant revision log entry'
    - 'enter nonprofit_org revision log entry'
    - 'revert grant revisions'
    - 'view grant revisions'
    - 'view nonprofit_org revisions'
removing: {  }
