adding:
  dependencies:
    config:
      - field.field.node.event.field_event_contact_email
      - field.field.node.event.field_event_contact_name
      - field.field.node.event.field_event_contact_phone
      - field.field.node.event.field_event_cost
      - field.field.node.event.field_event_sponsor
  hidden:
    field_event_contact_email: true
    field_event_contact_name: true
    field_event_contact_phone: true
    field_event_cost: true
    field_event_sponsor: true
removing:
  content:
    field_event_contact_information_heading:
      weight: 1
      settings: {  }
      third_party_settings: {  }
      region: content
