adding:
  dependencies:
    config:
      - field.field.node.event.field_event_contact_email
      - field.field.node.event.field_event_contact_name
      - field.field.node.event.field_event_contact_phone
      - field.field.node.event.field_event_cost
      - field.field.node.event.field_event_sponsor
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            config_split_sequence_hbaiuuv395gs4li5:
              uuid: 83b0cdb4-2a70-4e79-9f33-3d358a55023e
              region: main
              configuration:
                id: 'field_block:node:event:field_event_contact_email'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: email_mailto
                  label: visually_hidden
                  settings: {  }
                  third_party_settings: {  }
              weight: 12
              additional:
                layout_builder_styles_style:
                  block_margin_default_removed: block_margin_default_removed
              third_party_settings: {  }
            config_split_sequence_tintagg5gs9osvuj:
              uuid: 36b556e8-f950-4517-aa00-131f3a97b3bb
              region: main
              configuration:
                id: 'field_block:node:event:field_event_contact_name'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: string
                  label: visually_hidden
                  settings:
                    link_to_entity: false
                  third_party_settings: {  }
              weight: 10
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
            config_split_sequence_hmar8qcqm5ov1105:
              uuid: 4bcaf82b-de70-4f97-baa7-bfd7e4df31b4
              region: main
              configuration:
                id: 'field_block:node:event:field_event_contact_phone'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: telephone_link
                  label: visually_hidden
                  settings:
                    title: ''
                  third_party_settings: {  }
              weight: 11
              additional:
                layout_builder_styles_style:
                  block_margin_default_removed: block_margin_default_removed
              third_party_settings: {  }
            config_split_sequence_l6ct2hansrhd9uoh:
              uuid: c0eceed3-2b09-4d2e-8b41-c9223c6a4a1c
              region: main
              configuration:
                id: 'field_block:node:event:field_event_cost'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: string
                  label: inline
                  settings:
                    link_to_entity: false
                  third_party_settings: {  }
              weight: 7
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
            config_split_sequence_h9s9pbutfqso45us:
              uuid: f1cc0c2a-0235-4219-bac3-dae8e4f85ba4
              region: main
              configuration:
                id: 'field_block:node:event:field_event_sponsor'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: string
                  label: inline
                  settings:
                    link_to_entity: false
                  third_party_settings: {  }
              weight: 8
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
        -
          components:
            config_split_sequence_r9bg7cia74muac3k:
              uuid: f3f79a80-054b-47aa-9eca-0471afa6da45
              region: main
              configuration:
                id: 'field_block:node:event:field_event_contact_name'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: string
                  label: inline
                  settings:
                    link_to_entity: false
                  third_party_settings: {  }
              weight: 7
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
            config_split_sequence_unkaj2jq8djcg4gp:
              uuid: c4affbef-51d6-4e22-ad72-d74a7fc82584
              region: main
              configuration:
                id: 'field_block:node:event:field_event_contact_phone'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: telephone_link
                  label: inline
                  settings:
                    title: ''
                  third_party_settings: {  }
              weight: 8
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
            config_split_sequence_a322rpa6gdees3o9:
              uuid: c524e038-cb90-4d02-953f-9b48f49221e7
              region: main
              configuration:
                id: 'field_block:node:event:field_event_contact_email'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: email_mailto
                  label: inline
                  settings: {  }
                  third_party_settings: {  }
              weight: 9
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
            config_split_sequence_l7lqs41ukf3okupl:
              uuid: cc03d98b-cfd4-40dd-aea2-dc68602daa62
              region: main
              configuration:
                id: 'field_block:node:event:field_event_sponsor'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: string
                  label: above
                  settings:
                    link_to_entity: false
                  third_party_settings: {  }
              weight: 10
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
            config_split_sequence_e1tmcj9meunlljrj:
              uuid: 15a3755a-4057-46c1-8d9d-3e508c740151
              region: card_meta
              configuration:
                id: 'field_block:node:event:field_event_cost'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: string
                  label: visually_hidden
                  settings:
                    link_to_entity: false
                  third_party_settings: {  }
              weight: 10
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
  content:
    field_event_contact_email:
      type: basic_string
      label: above
      settings: {  }
      third_party_settings: {  }
      weight: 109
      region: content
    field_event_contact_name:
      type: string
      label: above
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 108
      region: content
    field_event_contact_phone:
      type: basic_string
      label: above
      settings: {  }
      third_party_settings: {  }
      weight: 110
      region: content
    field_event_cost:
      type: string
      label: above
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 106
      region: content
    field_event_sponsor:
      type: string
      label: above
      settings:
        link_to_entity: false
      third_party_settings: {  }
      weight: 107
      region: content
removing: {  }
