uids_base:
  header:
    type: header--secondary
    nav_style: toggle
    sticky: 1
  layout:
    container: page__container
  branding:
    legacy: 1
_core:
  default_config_hash: 2fJ8YMgkGYTSxbQ5jHCHfBvOtXM-YfYGwFSTefHN0t8
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
favicon:
  use_default: true
header:
  type: header--tertiary
  nav_style: toggle
  sticky: 0
  top_links_limit: 2
layout:
  container: page__container
branding:
  legacy: 1
