adding:
  dependencies:
    config:
      - node.type.mentor
      - node.type.scholar
      - node.type.student_profile
  permissions:
    - 'create mentor content'
    - 'create program fragments'
    - 'create scholar content'
    - 'create student_profile content'
    - 'delete mentor revisions'
    - 'delete own mentor content'
    - 'delete own scholar content'
    - 'delete own student_profile content'
    - 'delete scholar revisions'
    - 'delete student_profile revisions'
    - 'edit any mentor content'
    - 'edit any scholar content'
    - 'edit any student_profile content'
    - 'edit own mentor content'
    - 'edit own scholar content'
    - 'edit own student_profile content'
    - 'enter mentor revision log entry'
    - 'enter scholar revision log entry'
    - 'enter student_profile revision log entry'
    - 'override mentor published option'
    - 'override scholar published option'
    - 'revert mentor revisions'
    - 'revert person revisions'
    - 'revert scholar revisions'
    - 'revert student_profile revisions'
    - 'update own program fragments'
    - 'update program fragments'
    - 'view mentor revisions'
    - 'view program fragments'
    - 'view scholar revisions'
    - 'view student_profile revisions'
    - 'view thesis_defense revisions'
removing: {  }
