adding: {  }
removing:
  dependencies:
    config:
      - node.type.article
      - node.type.page
      - node.type.person
    module:
      - content_moderation
      - entity_usage
      - file
      - node
      - override_node_options
  permissions:
    - 'access entity usage statistics'
    - 'access files overview'
    - 'access media overview'
    - 'enter article revision log entry'
    - 'enter page revision log entry'
    - 'enter person revision log entry'
    - 'view any unpublished content'
    - 'view article revisions'
    - 'view latest version'
    - 'view own unpublished content'
    - 'view own unpublished media'
    - 'view page revisions'
    - 'view person revisions'
    - 'view the administration theme'
